### ISSUE TITLE
Number.Conversion is not used internally

### ISSUE THREAD

**Issue by Qqwy** [danielberkompas/number#12]
I am trying to use this package in combination with Ecto.

The numbers I have are saved in the Decimal format that is used by Ecto. When attempting to pass these to Number, an error is thrown, as this format is not recognized.

I attempted to implement the Number.Conversion protocol for this data type, but it turns out that this is not actually used for `Number.Currency.number_to_currency`.

**Comment by danielberkompas** [comment]
Good point! This is a bug and should be fixed.

In the meantime, do you need your Ecto field to be type `:decimal`? You can usually use the `:float` type instead, and then Ecto won't return those Decimal structs for you.

**Comment by Qqwy** [comment]
Yes. As I am dealing with monetary values, using floats would be unsafe.

:-)

**Comment by danielberkompas** [comment]
@Qqwy just for my own information, what makes using Floats unsafe for monetary values?

**Comment by thorsten-de** [comment]
Using floats to reperesent monetary values is unsafe because floats don't offer adequate precision for financial calculations. See http://blog.plataformatec.com.br/2014/09/floating-point-and-currency/ for example. 
In Elixir, floats are 64-bit IEEE floating point numbers, called double in many other languages, They are great for many scientific calculations, but for financial calculations, you should definitively go for something with arbitary decimal precision, like Decimal.

As for the main topic, implementing Number.Conversion protocol for Decimal is easy, so perhaps you could just use Number.Conversion.to_float to prepare each number.

**Comment by danielberkompas** [comment]
@Qqwy Finally got this fixed, and released a new version: `0.4.2`.

**Comment by Qqwy** [comment]
Thank you very much! :balloon:
